services:
#  kafka:
#    image: bitnami/kafka:3.2.1
#    ports:
#      - "9092:9092"
#    environment:
#      - KAFKA_ENABLE_KRAFT=yes
#      - KAFKA_CFG_PROCESS_ROLES=broker,controller
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
#      - KAFKA_BROKER_ID=1
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    volumes:
#      - ./dev/kafka:/scripts
#      - kafka_data:/var/lib/kafka
#
#  mongo_db:
#    image: mongo:4.4.10
#    ports:
#      - "27017:27017"
#    container_name: mongo_db
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#      MONGO_INITDB_DATABASE: xrust_beze
#    volumes:
#      - ./dev/mongo:/scripts
#      - mongo_data:/data/db
#
#  app:
#    image: xrust_beze:latest
#    container_name: main
#    env_file:
#      - .env
#    tty: true
#    ports:
#      - 8080:8080
#    restart: always
#    volumes:
#      - .:/app
#    depends_on:
#      - mongo_db
#      - kafka
#
#  # Сервис для AI дополнения ответов эксперта
#  ml_explanator:
#    build: ml_explanator
#    container_name: ml_explanator
#    ports:
#      - "8091:8091"
#    environment:
#      - MODEL_API_KEY=${MODEL_API_KEY}
#      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
#      - GOOGLE_CX=${GOOGLE_CX}
#
#  # WEB интерфейс для взаимодействия с ml_explanator. Но проде - отключить!
#  ml_check:
#    build: ml_check
#    container_name: ml_check
#    ports:
#      - "8501:8501"
#    environment:
#      - EXPLANATION_API_URL=http://ml_explanator:8091/explane
#    depends_on:
#      - ml_explanator

  ml_moderator:
    build: ml_moderator
    container_name: ml_moderator
    ports:
      - "8066:8066"

#volumes:
#  mongo_data:
#  kafka_data:
