version: '3.7'
services:
  kafka:
    image: bitnami/kafka:3.2.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./dev/kafka:/scripts
      - kafka_data:/var/lib/kafka

  mongo_db:
    image: mongo:4.4.10
    ports:
      - "27017:27017"
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: xrust_beze
    volumes:
      - ./dev/mongo:/scripts
      - mongo_data:/data/db

  app:
    image: xrust_beze:latest
    container_name: main
    env_file:
      - .env
    tty: true
    ports:
      - 8080:8080
    restart: always
    volumes:
      - .:/app
    depends_on:
      - mongo_db
      - kafka

  user_service:
    image: xrust_beze_user:latest
    container_name: user_service
    environment:
      - MONGO_URI=mongodb://admin:admin@mongo_db:27017/xrust_beze?authSource=admin
      - MONGO_DB_NAME=xrust_beze
      - HTTP_PORT=8080
      - GRPC_PORT=50051
    ports:
      - "8081:8080"  # HTTP порт (изменен, чтобы не конфликтовать с другими сервисами)
      - "50051:50051"  # gRPC порт
    restart: always
    depends_on:
      - mongo_db

volumes:
  mongo_data:
  kafka_data:
