// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/file/file.proto

package file

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MoveTempFileToAvatarsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveTempFileToAvatarsRequest) Reset() {
	*x = MoveTempFileToAvatarsRequest{}
	mi := &file_proto_file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveTempFileToAvatarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveTempFileToAvatarsRequest) ProtoMessage() {}

func (x *MoveTempFileToAvatarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveTempFileToAvatarsRequest.ProtoReflect.Descriptor instead.
func (*MoveTempFileToAvatarsRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{0}
}

func (x *MoveTempFileToAvatarsRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type MoveTempFileToAvatarsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveTempFileToAvatarsResponse) Reset() {
	*x = MoveTempFileToAvatarsResponse{}
	mi := &file_proto_file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveTempFileToAvatarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveTempFileToAvatarsResponse) ProtoMessage() {}

func (x *MoveTempFileToAvatarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveTempFileToAvatarsResponse.ProtoReflect.Descriptor instead.
func (*MoveTempFileToAvatarsResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{1}
}

func (x *MoveTempFileToAvatarsResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type DeleteAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAvatarRequest) Reset() {
	*x = DeleteAvatarRequest{}
	mi := &file_proto_file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAvatarRequest) ProtoMessage() {}

func (x *DeleteAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAvatarRequest.ProtoReflect.Descriptor instead.
func (*DeleteAvatarRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteAvatarRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type DeleteAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAvatarResponse) Reset() {
	*x = DeleteAvatarResponse{}
	mi := &file_proto_file_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAvatarResponse) ProtoMessage() {}

func (x *DeleteAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAvatarResponse.ProtoReflect.Descriptor instead.
func (*DeleteAvatarResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_file_proto_rawDescGZIP(), []int{3}
}

var File_proto_file_file_proto protoreflect.FileDescriptor

const file_proto_file_file_proto_rawDesc = "" +
	"\n" +
	"\x15proto/file/file.proto\x12\x04file\":\n" +
	"\x1cMoveTempFileToAvatarsRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\";\n" +
	"\x1dMoveTempFileToAvatarsResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"1\n" +
	"\x13DeleteAvatarRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"\x16\n" +
	"\x14DeleteAvatarResponse2\xb6\x01\n" +
	"\vFileService\x12`\n" +
	"\x15MoveTempFileToAvatars\x12\".file.MoveTempFileToAvatarsRequest\x1a#.file.MoveTempFileToAvatarsResponse\x12E\n" +
	"\fDeleteAvatar\x12\x19.file.DeleteAvatarRequest\x1a\x1a.file.DeleteAvatarResponseB\fZ\n" +
	"proto/fileb\x06proto3"

var (
	file_proto_file_file_proto_rawDescOnce sync.Once
	file_proto_file_file_proto_rawDescData []byte
)

func file_proto_file_file_proto_rawDescGZIP() []byte {
	file_proto_file_file_proto_rawDescOnce.Do(func() {
		file_proto_file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_file_file_proto_rawDesc), len(file_proto_file_file_proto_rawDesc)))
	})
	return file_proto_file_file_proto_rawDescData
}

var file_proto_file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_file_file_proto_goTypes = []any{
	(*MoveTempFileToAvatarsRequest)(nil),  // 0: file.MoveTempFileToAvatarsRequest
	(*MoveTempFileToAvatarsResponse)(nil), // 1: file.MoveTempFileToAvatarsResponse
	(*DeleteAvatarRequest)(nil),           // 2: file.DeleteAvatarRequest
	(*DeleteAvatarResponse)(nil),          // 3: file.DeleteAvatarResponse
}
var file_proto_file_file_proto_depIdxs = []int32{
	0, // 0: file.FileService.MoveTempFileToAvatars:input_type -> file.MoveTempFileToAvatarsRequest
	2, // 1: file.FileService.DeleteAvatar:input_type -> file.DeleteAvatarRequest
	1, // 2: file.FileService.MoveTempFileToAvatars:output_type -> file.MoveTempFileToAvatarsResponse
	3, // 3: file.FileService.DeleteAvatar:output_type -> file.DeleteAvatarResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_file_file_proto_init() }
func file_proto_file_file_proto_init() {
	if File_proto_file_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_file_file_proto_rawDesc), len(file_proto_file_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_file_file_proto_goTypes,
		DependencyIndexes: file_proto_file_file_proto_depIdxs,
		MessageInfos:      file_proto_file_file_proto_msgTypes,
	}.Build()
	File_proto_file_file_proto = out.File
	file_proto_file_file_proto_goTypes = nil
	file_proto_file_file_proto_depIdxs = nil
}
