http:
  port: 8080

services:
  user_service:
    host: "user_service"
    port: 50051

mongo:
  host: "mongo_db"
  port: 27017
  username: "admin"
  password: "admin"
  database: "xrust_beze"

kafka:
  addresses: ["kafka_xb:9092"]
  version: "3.8.0"
