http:
  port: 8080

services:
  user_service:
    host: "user_service"
    port: 50051
  file_service:
    host: "file_service"
    port: 50051
  structurization_service:
    host: "ml_explanator"
    port: 8091
    timeout: 120
    max_retries: 3

mongo:
  host: "mongo_db"
  port: 27017
  username: "admin"
  password: "admin"
  database: "xrust_beze"

kafka:
  addresses: ["kafka_xb:9092"]
  version: "3.8.0"
  study_material_topic: "xb.studymaterial.pub"
  voice_recognition_new_voice_topic: "xb.voice_recognition.new_voice"
  voice_recognition_voice_processed_topic: "xb.voice_recognition.voice_processed"
