http:
  port: 8080

services:
  user_service:
    host: "user_service"
    port: 50051
  structurization_service:
    host: "ml_explanator"
    port: 8091
    timeout: 120
    max_retries: 3

mongo:
  host: "mongo_db"
  port: 27017
  username: "admin"
  password: "admin"
  database: "xrust_beze"

kafka:
  addresses: ["kafka_xb:9092"]
  version: "3.8.0"
