http:
  port: 8080

grpc:
  port: 50051

kafka:
  addresses: ["kafka_xb:9092"]
  version: "3.8.0"
  study_material_topic: "xb.studymaterial.pub"

mongo:
  host: "mongo_db"
  port: 27017
  username: "admin"
  password: "admin"
  database: "xrust_beze"

services:
  file_service:
    host: file_service
    port: 50051
    timeout: 10
    max_retries: 3
  auth_service:
    host: auth_service
    port: 50051
    timeout: 10
    max_retries: 3
  user_service:
    host: user_service
    port: 50051
    timeout: 10
    max_retries: 3
  ai_tags_service:
    host: "ai_tags"
    port: 8087
    timeout: 120
    max_retries: 3
  rag_service:
    host: "RAG_service"
    port: 8929
    timeout: 120
    max_retries: 3
