mongo:
  host: "mongo_db"
  port: 27017
  username: "admin"
  password: "admin"
  database: "xrust_beze"

kafka:
  addresses: ["kafka_xb:9092"]
  version: "3.8.0"
  study_material_topic: "xb.studymaterial.pub"

services:
  file_service:
    host: "file_service"
    port: 50051
  ai_tags_service:
    host: "ai_tags"
    port: 8087
    timeout: 120
    max_retries: 3
