http:
  port: 8080

grpc:
  port: 50051

mongo:
  host: "mongo_db"
  port: 27017
  username: "admin"
  password: "admin"
  database: "xrust_beze"

services:
  file_service:
    host: file_service
    port: 50051
  auth_service:
    host: auth_service
    port: 50051
  moderation_service:
    host: "ml_moderator"
    port: 8066
    timeout: 120
    max_retries: 3

