# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nsfw.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'nsfw.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnsfw.proto\"3\n\x0b\x46ileRequest\x12\x13\n\x0b\x62ucket_name\x18\x01 \x01(\t\x12\x0f\n\x07\x66ile_id\x18\x02 \x01(\t\".\n\rProcessResult\x12\x0f\n\x07is_nsfw\x18\x01 \x01(\x08\x12\x0c\n\x04prob\x18\x02 \x01(\x02\x32<\n\x0bS3Processor\x12-\n\x0bProcessFile\x12\x0c.FileRequest\x1a\x0e.ProcessResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nsfw_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREQUEST']._serialized_start=14
  _globals['_FILEREQUEST']._serialized_end=65
  _globals['_PROCESSRESULT']._serialized_start=67
  _globals['_PROCESSRESULT']._serialized_end=113
  _globals['_S3PROCESSOR']._serialized_start=115
  _globals['_S3PROCESSOR']._serialized_end=175
# @@protoc_insertion_point(module_scope)
